server:
  port: 1919
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
spring:
  datasource:
    dynamic:
      strict: false
      primary: master
      datasource:
        master:
          username: root
          driver-class-name: com.mysql.jdbc.Driver
          password: root
          url: jdbc:mysql://localhost:3306/dczlxt?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
alipay:
  appId: 2021000122686477
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCMq1DwXPoRt5HRK0wRk3JC/HcZwS3+TS3LwEpurMKmqkXwf5NUAsBdtNM7eS822AxixG3O5pC3b5AFHqTnaStF3IsgS/X1YVgk9s2AOB5BrFRDb1hnwMOaeHsNIYRSXQLWePXJal8YIEUpYy+3I+CBEJd9/7t5pS/jftJmCWjdeYDHpjET571R5FMrN/qhs3WxIx5SIdJkt+GYswxl0wxDk1A+DzFQ+w3C3RHKqxJqxprGfibVBjJkSsTXC4/9Fjaam+bKfeFwg1/vsiqmdOeZAqZPD678Ff0HtxQZshA7x2ojBecYwMwv0A6m+b7kYkI+dindoP3nj9YgWfMqFOJ5AgMBAAECggEAaRuFIeTHMb/RY9KPRz6+DNFqCMNwo2h1xJ3Mv/+0fiYSlk4s/oQDysDXaMP3BGrQbmhJiGR9U6M3oKuyGftaSxwslJhNkukGnLARAzJrYTTrzWuASh4dyekmQLx/i69V9H1zYelqXrOWGgOz3osfMDD+kTYplg5Yxwq3GWkEgx8q0hlP4tDZ/S8/cYBTkJlHMlMJ/KfGkoo0Fa7pSwDVlviHnNWLn21+gnzJA2nD0+pGfKZGInfulAkT9BUgKDc9XmjjTs0XqkniB2fOg5WH3gy0CqHoOve1f4LvsHFpeM0Bmyn8Q0IaX9qzbDzDX/9iLuYIqrE5FjHmWzDP/5XREQKBgQDlvVCT8V0lwYsVn1hgSwA2esgiawNO94hsAmR0OAp0o42qPsE5Ke9dGSkpb4wSBtYnXufy0Yhx6jeOledFLUXT7Ner6nn4ap1IIrQ6kb8jJPOaXA4pIDI+IFVo1E9t3e8IZz03isvlQjZDMoXLFWvfDwloKxYPamwUSeza0wzQNQKBgQCcv5uLzzDU8CGM9pGakwZJTH/GjgM7ydFhwOMvKySSgLuqtKPteObjAF90hx/nmLv3gu9BLbc94E5xY/VfGrM7cixr5Huig4UYQmC0/onoty5C6ZyjOApTDaA1RxVzlPhI7pWmV4SG+jRfwIw7d5TB4/s6EaMMb8sN5CCYgf6ZtQKBgGrlgb60yeCtg6fV8usrOrgevUy2el2d88499rvU75iCGYKjnIiaqJOrB2oOSyCAKdk74bUsJc7Lanpf6bJYdGs9gsStX39lLDXKYA34jvUtVmP2fWhJYNdjeBpE34iBgZ1pXCSh4mmUO2dc9MAgAYdSmc/sbGFT5WIzW5AeL5IZAoGACGPpO46Xmo5P/W+lU5TTHVFO9Z3cZnLjFkxw3LF+f6kMYpLQw4FZOoVmlqI0/vyZ8yG7FM4RpOpAyKkFFVYkieYOoqfURlqr4SSMcKO/VgmYHFTM4Z+6Tb/I95EagNlUgPLkZ8b/fQofi5CO8Q/xkn9Vj0IqbBv/znqLlB5BNpECgYA0Ot6Gc+dpfCc2bMdyZKu6fq3+Ak2sv+ufhuS2tg21rEu5mpiphSoMyPYPHtXi3LhG8MHjKGczO5VGei5C4NX7Dj0AfB/Ziu4Lpx1/4/6tFiEXGH6nXwBlk+HSTqHvwVW1JMJxAXacPIaJSWKJ29kK9SWSFD20iGXDLKOc8rHfSg==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvDhA9ASSzf0GyY2ndq/nQOBCrUNgjQxg1dLW7JFgk3ghtQ24Pz4DTKzNylbd2vQIaC3PNZ0yXJwAPlnyRF/J558CzwNgjtPUK7ka1HehzkDP+k/EPoDho5t1h6838sjSvG90CU5/4fz9Q2owv4kQUWdgtPTN9vNP9BBabPEfSZyiii7nMOsEBq6wXDv7qlg89IRa3anDjgN02OnPWavkpL8nux/SaafHTcrgMJQvIKVDj0CiKds8IlCzntJhMzCIdcbTDJ1M8Pi32jZfYQLjIM5VwEbmEXt1ltwu+EyIWOEykuaoeM8ljjTOAQf8HAbhx5djk141jAr6/hYQciZKzwIDAQAB
  notifyUrl:
