server:
  port: 1919
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
spring:
  datasource:
    dynamic:
      strict: false
      primary: master
      datasource:
        master:
          username: root
          driver-class-name: com.mysql.jdbc.Driver
          password: root
          url: jdbc:mysql://localhost:3306/dczlxt?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8