spring:
  profiles:
    active: prod
server:
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  undertow:
    #io-threads: 16
    #worker-threads: 256
    buffer-size: 1024
    direct-buffers: true

logging:
  config: classpath:log4j2-spring.xml
  file:
    path: './log'

mybatis-plus:
  # MyBatis ?????????????? MyBatis ??????????? configLocation ??
  # config-location: classpath:mybatis-config.xml
  # MyBatis Mapper ???? XML ????????? Mapper ???????
  mapper-locations:
    - classpath:/mapper/*/*Mapper.xml
    # MyBaits ???????????????????????? ???????package?????????
  type-aliases-package: com.wengegroup.model.entity.*.*
  # ???????? # ????? * ?? ; ??
  # type-enums-package: com.abbottliu.sys.enums,com.abbottliu.enums
  # ??????? MyBatis XML ???????????
  check-config-location: false
  # ExecutorType.SIMPLE???????????????????????????????????PreparedStatement?
  # ExecutorType.REUSE????????????????PreparedStatement?
  # ExecutorType.BATCH???????????????????
  # executor-type: simple
  configuration:
    # ?????????????camel case???
    map-underscore-to-camel-case: true
    #??JdbcTypeForNull, oracle???????
    jdbc-type-for-null: null
    cache-enabled: false
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ???????
    # lazy-loading-enabled: true
  global-config:
    # ??mapper ????
    db-config:
      # ????
      id-type: AUTO
      # ??????????????? true:????????????
      table-underline: true
      #??????????
      # capital-mode: true
      #??????
#      logic-delete-value: "now()"
#      logic-not-delete-value: "null"
############# ????PageHelper?? #############
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  pageSizeZero: true
  params: count=countSql

knife4j:
  enable: true